language: python
python: 3.5
cache: pip
env:
  - TOXENV=py27
  - TOXENV=py27-pandas
  - TOXENV=py34
  - TOXENV=py34-pandas
  - TOXENV=py35
  - TOXENV=py35-pandas
  - TOXENV=pypy
  - TOXENV=flake8
  - TOXENV=docs
install:
  - travis_retry pip install tox
script:
  - travis_retry tox
