language: python
cache: pip
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27-pandas
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
  - python: 3.4
    env: TOXENV=py34-pandas
  - python: 3.5
    env: TOXENV=py35
  - python: 3.5
    env: TOXENV=py35-pandas
  - python: 3.6
    env: TOXENV=py36
  - python: 3.6
    env: TOXENV=py36-pandas
  - python: pypy
    env: TOXENV=pypy
install:
  - travis_retry pip install tox
script:
  - travis_retry tox
